-- Generated by Mocodo 4.2.8

-- Table: Utilisateur
CREATE TABLE Utilisateur (
  id            INT PRIMARY KEY AUTO_INCREMENT,
  nom           VARCHAR(100) NOT NULL,
  prenom        VARCHAR(100) NOT NULL,
  courriel      VARCHAR(320) NOT NULL UNIQUE,
  mot_de_passe  VARCHAR(255) NOT NULL,
  role          ENUM('utilisateur', 'administrateur') NOT NULL
);

-- Table: Attraction
CREATE TABLE Attraction (
  id            INT PRIMARY KEY AUTO_INCREMENT,
  nom           VARCHAR(150) NOT NULL,
  description   TEXT NULL,
  categorie_id  INT NOT NULL,
  image         VARCHAR(255) NULL,
  FOREIGN KEY (categorie_id) REFERENCES Categorie(id)
);

-- Table: Catégorie
CREATE TABLE Categorie (
  id            INT PRIMARY KEY AUTO_INCREMENT,
  nom           VARCHAR(100) NOT NULL,
  description   TEXT NULL
);

-- Table: Réservation
CREATE TABLE Reservation (
  id              INT PRIMARY KEY AUTO_INCREMENT,
  utilisateur_id  INT NOT NULL,
  attraction_id   INT NOT NULL,
  date_visite     DATE NOT NULL,
  statut          ENUM('confirmée', 'annulée') NOT NULL,
  FOREIGN KEY (utilisateur_id) REFERENCES Utilisateur(id),
  FOREIGN KEY (attraction_id) REFERENCES Attraction(id)
);

-- Table: Message
CREATE TABLE Message (
  id              INT PRIMARY KEY AUTO_INCREMENT,
  utilisateur_id  INT NOT NULL,
  nom             VARCHAR(80) NOT NULL,
  prénom          VARCHAR(80) NOT NULL,
  contenu         TEXT NOT NULL,
  date_envoi      DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (utilisateur_id) REFERENCES Utilisateur(id)
);